development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: TMopen_development
  pool: 5
  username: root
  password:
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: TMopen_test
  pool: 5
  username: root
  password:
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: TMopen_production
  pool: 5
  username: root
  password:
  host: 127.0.0.1